spring.application.name=server

spring.datasource.url=jdbc:h2:mem:banking_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username= root
spring.datasource.password=root123

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=7ca5c89189b501793d2aed198523aacd7af48a9a85084cfc5d0706ca58fc5ef1
jwt.expiration=3600000

cors.allowed-origins=http://localhost:5173

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.jackson.deserialization.fail-on-unknown-properties=true
